import { useMemo, useState } from 'react';
import { CheckCircle, Eye, Pencil, Plus, Search, X, XCircle } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { EmptyState } from '@/components/common/EmptyState';
import { PageHeader } from '@/components/common/PageHeader';
import { StatusBadge } from '@/components/common/StatusBadge';
import { PurchaseOrderForm } from '@/components/forms/PurchaseOrderForm';
import { useCancelPurchaseOrder, useConfirmPurchaseOrder, useCreatePurchaseOrder, usePurchaseOrders, useUpdatePurchaseOrder } from '@/hooks/usePurchaseOrders';
import { useContacts } from '@/hooks/useContacts';
import { formatCurrency } from '@/lib/format';
import type { PurchaseOrder, PurchaseOrderInput, PurchaseOrderStatus } from '@/types/purchaseOrder';

const statusValue = (status: PurchaseOrderStatus) => status.toLowerCase() as 'draft' | 'confirmed' | 'cancelled';
const dialogClass = 'fixed inset-0 z-50 flex items-center justify-center bg-black/30 p-4';

export function PurchaseOrders() {
  const [search, setSearch] = useState(''); const [status, setStatus] = useState<'ALL' | PurchaseOrderStatus>('ALL'); const [vendorId, setVendorId] = useState(''); const [fromDate, setFromDate] = useState(''); const [toDate, setToDate] = useState('');
  const [editing, setEditing] = useState<PurchaseOrder | null>(null); const [viewing, setViewing] = useState<PurchaseOrder | null>(null); const [confirming, setConfirming] = useState<{ order: PurchaseOrder; action: 'confirm' | 'cancel' } | null>(null); const [createOpen, setCreateOpen] = useState(false);
  const filters = useMemo(() => ({ search: search || undefined, status, vendorId: vendorId || undefined, fromDate: fromDate || undefined, toDate: toDate || undefined }), [search, status, vendorId, fromDate, toDate]);
  const { data: orders = [], isLoading, isError, refetch } = usePurchaseOrders(filters); const { data: contacts = [] } = useContacts({ type: 'ALL' }); const vendors = contacts.filter(contact => contact.type === 'VENDOR' || contact.type === 'BOTH');
  const create = useCreatePurchaseOrder(); const update = useUpdatePurchaseOrder(); const confirm = useConfirmPurchaseOrder(); const cancel = useCancelPurchaseOrder();
  const clear = () => { setSearch(''); setStatus('ALL'); setVendorId(''); setFromDate(''); setToDate(''); }; const hasFilters = !!(search || status !== 'ALL' || vendorId || fromDate || toDate);
  const closeForm = () => { setCreateOpen(false); setEditing(null); };
  const submit = (data: PurchaseOrderInput) => { if (editing) update.mutate({ id: editing.id, input: data }, { onSuccess: closeForm }); else create.mutate(data, { onSuccess: closeForm }); };
  const performAction = () => { if (!confirming) return; const fn = confirming.action === 'confirm' ? confirm : cancel; fn.mutate(confirming.order.id, { onSuccess: () => setConfirming(null) }); };

  return <><PageHeader title="Purchase Orders" description="Create and manage purchase orders for vendors." actions={<Button onClick={() => setCreateOpen(true)} className="bg-[#1a2a3a] hover:bg-[#2a3f56]"><Plus className="mr-1.5 h-4 w-4" />Create Purchase Order</Button>} />
    <div className="mb-4 rounded-lg border border-[#e5e7eb] bg-white p-4"><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-5"><label className="relative"><Search className="absolute left-3 top-2.5 h-4 w-4 text-[#6b7280]" /><input aria-label="Search purchase orders" placeholder="Search order or vendor" value={search} onChange={event => setSearch(event.target.value)} className="w-full rounded-md border border-[#e5e7eb] py-2 pl-9 pr-3 text-sm" /></label><select aria-label="Filter by status" value={status} onChange={event => setStatus(event.target.value as 'ALL' | PurchaseOrderStatus)} className="rounded-md border p-2 text-sm"><option value="ALL">All statuses</option><option>Draft</option><option>Confirmed</option><option>Cancelled</option></select><select aria-label="Filter by vendor" value={vendorId} onChange={event => setVendorId(event.target.value)} className="rounded-md border p-2 text-sm"><option value="">All vendors</option>{vendors.map(vendor => <option key={vendor.id} value={vendor.id}>{vendor.name}</option>)}</select><input aria-label="Date from" type="date" value={fromDate} onChange={event => setFromDate(event.target.value)} className="rounded-md border p-2 text-sm" /><input aria-label="Date to" type="date" value={toDate} onChange={event => setToDate(event.target.value)} className="rounded-md border p-2 text-sm" /></div>{hasFilters && <Button variant="ghost" size="sm" onClick={clear} className="mt-3">Clear Filters</Button>}</div>
    {isError ? <div className="py-12 text-center"><p className="text-sm text-[#6b7280]">Unable to load purchase orders.</p><Button variant="outline" className="mt-3" onClick={() => refetch()}>Try again</Button></div> : isLoading ? <div className="rounded-lg border bg-white p-8 text-sm text-[#6b7280]">Loading purchase orders…</div> : orders.length === 0 ? <EmptyState icon={<Search className="h-12 w-12 text-[#d1d5db]" />} title={hasFilters ? 'No matching purchase orders' : 'No purchase orders yet'} description={hasFilters ? 'Adjust or clear your filters to see more records.' : 'Create a purchase order to manage vendor purchases.'} action={!hasFilters ? <Button onClick={() => setCreateOpen(true)}><Plus className="mr-1 h-4 w-4" />Create Purchase Order</Button> : undefined} /> : <div className="overflow-x-auto rounded-lg border border-[#e5e7eb] bg-white"><table className="min-w-[850px] w-full text-sm"><thead className="bg-[#f9fafb] text-left text-xs uppercase tracking-wide text-[#6b7280]"><tr><th className="p-4">Order Number</th><th className="p-4">Order Date</th><th className="p-4">Vendor</th><th className="p-4 text-center">Items</th><th className="p-4 text-right">Total Amount</th><th className="p-4">Status</th><th className="p-4 text-right">Actions</th></tr></thead><tbody>{orders.map(order => <tr key={order.id} className="border-t border-[#e5e7eb]"><td className="p-4 font-medium text-[#1a2332]">{order.orderNumber}</td><td className="p-4">{order.orderDate}</td><td className="p-4">{order.vendorName}</td><td className="p-4 text-center">{order.items.length}</td><td className="p-4 text-right font-medium">{formatCurrency(order.totalAmount)}</td><td className="p-4"><StatusBadge status={statusValue(order.status)} /></td><td className="p-4"><div className="flex justify-end gap-1"><Button aria-label={`View ${order.orderNumber}`} variant="ghost" size="icon" onClick={() => setViewing(order)}><Eye className="h-4 w-4" /></Button>{order.status === 'Draft' && <><Button aria-label={`Edit ${order.orderNumber}`} variant="ghost" size="icon" onClick={() => setEditing(order)}><Pencil className="h-4 w-4" /></Button><Button aria-label={`Confirm ${order.orderNumber}`} variant="ghost" size="icon" onClick={() => setConfirming({ order, action: 'confirm' })}><CheckCircle className="h-4 w-4 text-emerald-700" /></Button></>}{order.status !== 'Cancelled' && <Button aria-label={`Cancel ${order.orderNumber}`} variant="ghost" size="icon" onClick={() => setConfirming({ order, action: 'cancel' })}><XCircle className="h-4 w-4 text-red-700" /></Button>}</div></td></tr>)}</tbody></table></div>}
    {(createOpen || editing) && <div className={dialogClass} role="dialog" aria-modal="true" aria-label={editing ? 'Edit Purchase Order' : 'Create Purchase Order'}><div className="max-h-[90vh] w-full max-w-5xl overflow-y-auto rounded-lg bg-white p-6 shadow-xl"><div className="mb-5 flex items-center justify-between"><h2 className="text-lg font-semibold">{editing ? 'Edit Purchase Order' : 'Create Purchase Order'}</h2><Button variant="ghost" size="icon" aria-label="Close" onClick={closeForm}><X className="h-4 w-4" /></Button></div><PurchaseOrderForm initialData={editing} onSubmit={submit} onCancel={closeForm} isSubmitting={create.isPending || update.isPending} /></div></div>}
    {viewing && <div className={dialogClass} role="dialog" aria-modal="true" aria-label="Purchase order details"><div className="max-h-[90vh] w-full max-w-3xl overflow-y-auto rounded-lg bg-white p-6 shadow-xl"><div className="mb-5 flex justify-between"><div><h2 className="text-lg font-semibold">{viewing.orderNumber}</h2><p className="text-sm text-[#6b7280]">{viewing.orderDate} · {viewing.vendorName}</p></div><Button variant="ghost" size="icon" aria-label="Close" onClick={() => setViewing(null)}><X className="h-4 w-4" /></Button></div><StatusBadge status={statusValue(viewing.status)} /><table className="mt-4 w-full text-sm"><thead className="border-b text-left text-xs uppercase text-[#6b7280]"><tr><th className="py-2">Product</th><th>Qty</th><th className="text-right">Price</th><th className="text-right">Tax</th><th className="text-right">Line Total</th></tr></thead><tbody>{viewing.items.map(item => <tr key={item.id} className="border-b"><td className="py-2">{item.productName}</td><td>{item.quantity}</td><td className="text-right">{formatCurrency(item.unitPrice)}</td><td className="text-right">{item.taxRate * 100}%</td><td className="text-right">{formatCurrency(item.lineTotal)}</td></tr>)}</tbody></table><div className="mt-4 ml-auto w-56 space-y-1 text-sm"><div className="flex justify-between"><span>Subtotal</span><span>{formatCurrency(viewing.subtotal)}</span></div><div className="flex justify-between"><span>Tax</span><span>{formatCurrency(viewing.taxAmount)}</span></div><div className="flex justify-between border-t pt-1 font-semibold"><span>Total</span><span>{formatCurrency(viewing.totalAmount)}</span></div></div>{viewing.notes && <p className="mt-5 border-t pt-4 text-sm"><span className="font-medium">Notes: </span>{viewing.notes}</p>}</div></div>}
    {confirming && <div className={dialogClass} role="alertdialog" aria-modal="true" aria-label={`${confirming.action} purchase order`}><div className="w-full max-w-md rounded-lg bg-white p-6 shadow-xl"><h2 className="text-lg font-semibold">{confirming.action === 'confirm' ? 'Confirm purchase order?' : 'Cancel purchase order?'}</h2><p className="mt-2 text-sm text-[#6b7280]">{confirming.action === 'confirm' ? `Confirm ${confirming.order.orderNumber}? It will no longer be editable.` : `Cancel ${confirming.order.orderNumber}?`}</p><div className="mt-5 flex justify-end gap-3"><Button variant="outline" onClick={() => setConfirming(null)}>Keep editing</Button><Button onClick={performAction} disabled={confirm.isPending || cancel.isPending} className={confirming.action === 'cancel' ? 'bg-red-700 hover:bg-red-800' : 'bg-[#1a2a3a] hover:bg-[#2a3f56]'}>{confirming.action === 'confirm' ? 'Confirm' : 'Cancel Order'}</Button></div></div></div>}
  </>;
}
