import { contactService } from '@/services/contactService';
import { productService } from '@/services/productService';
import { purchaseOrderService } from '@/services/purchaseOrderService';
import type { PurchaseOrderItem } from '@/types/purchaseOrder';
import type { VendorBill, VendorBillFilters, VendorBillInput } from '@/types/vendorBill';

let bills: VendorBill[] = [{ id: 'vb-1', billNumber: 'VB-1001', billDate: '2025-02-05', dueDate: '2025-03-05', purchaseOrderId: 'po-1', purchaseOrderNumber: 'PO-1001', vendorId: '2', vendorName: 'Priya Sharma', status: 'Posted', items: [{ id: 'vbi-1', productId: '1', productName: 'Office Desk', quantity: 3, unitPrice: 18000, taxRate: .18, lineTotal: 63720 }], subtotal: 54000, taxAmount: 9720, totalAmount: 63720, paidAmount: 0, balanceDue: 63720, notes: 'Net 30 terms.' }];
let nextId = 2;
const delay = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));
const round = (value: number) => Math.round(value * 100) / 100;
const totals = (items: PurchaseOrderItem[]) => { const subtotal = round(items.reduce((sum, item) => sum + item.quantity * item.unitPrice, 0)); const taxAmount = round(items.reduce((sum, item) => sum + item.quantity * item.unitPrice * item.taxRate, 0)); return { subtotal, taxAmount, totalAmount: round(subtotal + taxAmount) }; };
const buildItems = async (input: VendorBillInput['items']): Promise<PurchaseOrderItem[]> => { const products = await productService.getProducts(); return input.map((item, index) => ({ ...item, id: `vbi-${Date.now()}-${index}`, productName: products.find(product => product.id === item.productId)?.name ?? '', taxRate: item.taxRate || 0, lineTotal: round(item.quantity * item.unitPrice * (1 + (item.taxRate || 0))) })); };

export const vendorBillService = {
  async getVendorBills(filters?: VendorBillFilters) { await delay(250); return bills.filter(bill => { const search = filters?.search?.toLowerCase(); return (!search || bill.billNumber.toLowerCase().includes(search) || bill.vendorName?.toLowerCase().includes(search) || bill.purchaseOrderNumber?.toLowerCase().includes(search)) && (!filters?.status || filters.status === 'ALL' || bill.status === filters.status) && (!filters?.vendorId || bill.vendorId === filters.vendorId) && (!filters?.fromDate || bill.billDate >= filters.fromDate) && (!filters?.toDate || bill.billDate <= filters.toDate); }); },
  async createVendorBill(input: VendorBillInput) { await delay(300); const contacts = await contactService.getContacts(); const vendor = contacts.find(contact => contact.id === input.vendorId); if (!vendor || !['VENDOR', 'BOTH'].includes(vendor.type)) throw new Error('Select a valid vendor.'); const po = input.purchaseOrderId ? (await purchaseOrderService.getPurchaseOrders()).find(order => order.id === input.purchaseOrderId && order.status === 'Confirmed') : undefined; if (input.purchaseOrderId && !po) throw new Error('Select a confirmed purchase order.'); if (po && po.vendorId !== input.vendorId) throw new Error('Purchase order vendor does not match.'); const items = await buildItems(input.items); const amount = totals(items); const bill: VendorBill = { id: `vb-${nextId++}`, ...input, vendorName: vendor.name, purchaseOrderNumber: po?.orderNumber, status: 'Draft', items, ...amount, paidAmount: 0, balanceDue: amount.totalAmount, notes: input.notes || '' }; bills = [...bills, bill]; return bill; },
  async updateVendorBill(id: string, input: VendorBillInput) { await delay(300); const existing = bills.find(bill => bill.id === id); if (!existing) throw new Error('Vendor bill not found.'); if (existing.status !== 'Draft') throw new Error('Only draft vendor bills can be edited.'); const contacts = await contactService.getContacts(); const vendor = contacts.find(contact => contact.id === input.vendorId); if (!vendor || !['VENDOR', 'BOTH'].includes(vendor.type)) throw new Error('Select a valid vendor.'); const po = input.purchaseOrderId ? (await purchaseOrderService.getPurchaseOrders()).find(order => order.id === input.purchaseOrderId && order.status === 'Confirmed') : undefined; const items = await buildItems(input.items); const amount = totals(items); const updated: VendorBill = { ...existing, ...input, vendorName: vendor.name, purchaseOrderNumber: po?.orderNumber, items, ...amount, balanceDue: round(amount.totalAmount - existing.paidAmount), notes: input.notes || '' }; bills = bills.map(bill => bill.id === id ? updated : bill); return updated; },
  async postVendorBill(id: string) { await delay(250); const bill = bills.find(value => value.id === id); if (!bill || bill.status !== 'Draft') throw new Error('Only draft vendor bills can be posted.'); const updated = { ...bill, status: 'Posted' as const }; bills = bills.map(value => value.id === id ? updated : value); return updated; },
  async cancelVendorBill(id: string) { await delay(250); const bill = bills.find(value => value.id === id); if (!bill || !['Draft', 'Posted'].includes(bill.status)) throw new Error('Vendor bill cannot be cancelled.'); const updated = { ...bill, status: 'Cancelled' as const }; bills = bills.map(value => value.id === id ? updated : value); return updated; },
};
