import { vendorBillService } from '@/services/vendorBillService';
import type { VendorPayment, VendorPaymentFilters, VendorPaymentInput } from '@/types/vendorPayment';
let payments: VendorPayment[] = []; let nextId = 1; const delay = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));
export const vendorPaymentService = {
  async getVendorPayments(filters?: VendorPaymentFilters) { await delay(250); return payments.filter(payment => { const search = filters?.search?.toLowerCase(); return (!search || payment.paymentNumber.toLowerCase().includes(search) || payment.vendorName?.toLowerCase().includes(search) || payment.billNumber?.toLowerCase().includes(search) || payment.reference?.toLowerCase().includes(search)) && (!filters?.status || filters.status === 'ALL' || payment.status === filters.status) && (!filters?.vendorId || payment.vendorId === filters.vendorId) && (!filters?.paymentMethod || filters.paymentMethod === 'ALL' || payment.paymentMethod === filters.paymentMethod) && (!filters?.fromDate || payment.paymentDate >= filters.fromDate) && (!filters?.toDate || payment.paymentDate <= filters.toDate); }); },
  async createVendorPayment(input: VendorPaymentInput) { await delay(300); const bill = (await vendorBillService.getPayableVendorBills()).find(value => value.id === input.vendorBillId); if (!bill) throw new Error('Select a payable vendor bill.'); if (input.amount <= 0 || input.amount > bill.balanceDue) throw new Error('Amount must be greater than zero and no more than balance due.'); const payment: VendorPayment = { id: `vp-${nextId++}`, ...input, vendorId: bill.vendorId, vendorName: bill.vendorName, billNumber: bill.billNumber, status: 'Draft', notes: input.notes || '', reference: input.reference || '' }; payments = [...payments, payment]; return payment; },
  async updateVendorPayment(id: string, input: VendorPaymentInput) { await delay(300); const existing = payments.find(payment => payment.id === id); if (!existing || existing.status !== 'Draft') throw new Error('Only draft payments can be edited.'); const bill = (await vendorBillService.getPayableVendorBills()).find(value => value.id === input.vendorBillId); if (!bill || input.amount <= 0 || input.amount > bill.balanceDue) throw new Error('Amount must not exceed the selected bill balance due.'); const updated: VendorPayment = { ...existing, ...input, vendorId: bill.vendorId, vendorName: bill.vendorName, billNumber: bill.billNumber, notes: input.notes || '', reference: input.reference || '' }; payments = payments.map(payment => payment.id === id ? updated : payment); return updated; },
  async postVendorPayment(id: string) { await delay(250); const payment = payments.find(value => value.id === id); if (!payment || payment.status !== 'Draft') throw new Error('Only draft payments can be posted.'); await vendorBillService.applyPayment(payment.vendorBillId, payment.amount); const updated = { ...payment, status: 'Posted' as const }; payments = payments.map(value => value.id === id ? updated : value); return updated; },
  async cancelVendorPayment(id: string) { await delay(250); const payment = payments.find(value => value.id === id); if (!payment || payment.status === 'Cancelled') throw new Error('Payment cannot be cancelled.'); if (payment.status === 'Posted') await vendorBillService.reversePayment(payment.vendorBillId, payment.amount); const updated = { ...payment, status: 'Cancelled' as const }; payments = payments.map(value => value.id === id ? updated : value); return updated; },
};
